// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: person.proto

package proto

import (
	driver "database/sql/driver"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	p "google.golang.org/protobuf/proto"
	gorm "gorm.io/gorm"
	schema "gorm.io/gorm/schema"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (t *Person) Scan(val interface{}) error {
	return p.Unmarshal(val.([]byte), t)
}

func (t *Person) Value() (driver.Value, error) {
	if t == nil {
		t = &Person{}
	}
	return p.Marshal(t)
}

func (*Person) GormDBDataType(*gorm.DB, *schema.Field) string {
	return "blob"
}

func (t *Dog) Scan(val interface{}) error {
	return p.Unmarshal(val.([]byte), t)
}

func (t *Dog) Value() (driver.Value, error) {
	if t == nil {
		t = &Dog{}
	}
	return p.Marshal(t)
}

func (*Dog) GormDBDataType(*gorm.DB, *schema.Field) string {
	return "blob"
}

func (t *Dog_Ms) Scan(val interface{}) error {
	return p.Unmarshal(val.([]byte), t)
}

func (t *Dog_Ms) Value() (driver.Value, error) {
	if t == nil {
		t = &Dog_Ms{}
	}
	return p.Marshal(t)
}

func (*Dog_Ms) GormDBDataType(*gorm.DB, *schema.Field) string {
	return "blob"
}
